

spring:
  security:
    oauth2:
      client:
        provider:
          tacocloud:
            issuer-uri: http://localhost:9000
#            authorization-uri: http://localhost:9000/oauth2/authorize
#            token-uri: http://localhost:9000/oauth2/token
#            jwk-set-uri: http://localhost:9000/oauth2/jwks
#            user-info-uri: http://localhost:9000/userinfo
#            user-name-attribute: sub
        registration:
          taco-admin-client:
            provider: tacocloud
            client-id: taco-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri:
              "http://127.0.0.1:9191/login/oauth2/code/taco-admin-client"
            scope: writeIngredients,deleteIngredients,openid
server:
  port: 9191
#logging:
#  level:
#    root: debug